### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by Jinntty** [mazzalab/fastqwiper#10]
Hello, my fastq file is damaged and I want to use your software to repair it. But now I encounter some problems. Fastq1 reports an error and fastq2 is still running. How to solve it?

2023-10-30 01:17:27,753 - fastq_wiper/wiper.py(print_log_during_reading) - [34mINFO[0m - Cleaned 375000000 reads
2023-10-30 01:17:54,546 - fastq_wiper/wiper.py(print_log_during_reading) - [34mINFO[0m - Cleaned 375500000 reads
Traceback (most recent call last):
  File "~/miniconda3/bin/fastqwiper", line 11, in <module>
    sys.exit(wipe_fastq())
  File "~/miniconda3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "~/miniconda3/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "~/miniconda3/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/miniconda3/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "~/miniconda3/lib/python3.9/site-packages/fastq_wiper/wiper.py", line 363, in wipe_fastq
    qual = fix_qual_line(line, checkpoint_flags)
  File "~/miniconda3/lib/python3.9/site-packages/fastq_wiper/wiper.py", line 115, in fix_qual_line
    min_ascii = min(ord(c) for c in line)
ValueError: min() arg is an empty sequence

**Comment by mazzalab** [comment]
Hi, can you share with us fastq1? We may better solve the issue with the file in hand

**Comment by mazzalab** [comment]
We have released a new version that should fix this issue. Please give us a feedback
